version: '2'
services:
  #  redis:
  #    image: redis
  #    ports:
  #      - "6379:6379"
  mysql:
    image: mysql:5.7
    volumes:
    - "database:/var/lib/mysql"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: Asia/Shanghai
      MYSQL_USER: root
      MYSQL_HOST: "%"
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: hsweb
    ports:
    - "13306:3306"
  hsweb-antd:
    image: registry.cn-shenzhen.aliyuncs.com/zmcsoft/hsweb-antd
    links:
      - "mysql:mysql"
    volumes:
      - "data:/data"
    environment:
      spring.profiles.active: prod
    ports:
      - "8090:8090"
    depends_on:
      - mysql
volumes:
  database:
